ARG DRIFTWATCH_IMAGE_TARGET=runtime

# --- Stage 0: exact source archive for inspection ---------------------------
FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6 AS source
WORKDIR /source/driftwatch
COPY . .
RUN tar -czf /driftwatch-source.tar.gz -C /source driftwatch

# --- Stage 1: build the SPA -------------------------------------------------
FROM node:25-slim@sha256:81db02c4b671288a03915da9534dbd54f96d0e7c24d80ccc54f5b36b2e684370 AS web
WORKDIR /web
COPY web/package.json web/package-lock.json ./
RUN npm ci
COPY web/ ./
RUN npm run build

# --- Stage 2: build an application wheel with a locked backend -------------
FROM python:3.12.15-slim@sha256:05cda9777409a9c3ffddd94a4c476b79f0769a0b4857f0c7ed9226b6800b0d6f AS wheel-builder
ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /build
COPY pyproject.toml requirements-build.in requirements-build.lock ./
COPY requirements-installer.lock ./
RUN pip install --require-hashes --only-binary=:all: -r requirements-installer.lock
# Force wheels for the build toolchain itself. Otherwise installing a hashed
# sdist could start a second, unconstrained PEP 517 build environment.
RUN python -c "from pathlib import Path; import tomllib; \
declared=tomllib.loads(Path('pyproject.toml').read_text())['build-system']['requires']; \
expected=[line.strip() for line in Path('requirements-build.in').read_text().splitlines() \
if line.strip() and not line.lstrip().startswith('#')]; \
assert declared == expected, 'build-system requirements and build input differ'" \
    && pip install --require-hashes --only-binary=:all: -r requirements-build.lock
COPY README.md LICENSE THIRD_PARTY_NOTICES.md ./
COPY src ./src
RUN pip wheel --no-deps --no-build-isolation --wheel-dir /wheels .

# --- Stage 3: pinned glibc runtime and independently rebuilt X.org fixes ----
FROM cgr.dev/chainguard/wolfi-base:latest@sha256:05d24163df148be377275af8374c16523a1dc7e19bf4f1c689784791553c5e45 AS native-base
COPY docker/native/api.apk.lock /native/api.apk.lock
RUN test "$(apk --print-arch)" = x86_64 \
    && apk add --no-cache $(awk '{sub(/\r$/, "")} NF && !/^#/' /native/api.apk.lock)

FROM native-base AS native-builder
COPY docker/native/build.apk.lock /native/build.apk.lock
RUN apk add --no-cache $(awk '{sub(/\r$/, "")} NF && !/^#/' /native/build.apk.lock)
COPY docker/native /recipe
RUN python /recipe/verify_runtime.py build \
    && python /recipe/build_backports.py

FROM native-base AS python-base
ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PATH=/opt/venv/bin:$PATH
WORKDIR /app
COPY requirements.lock requirements-installer.lock ./
COPY docker/native/verify_runtime.py /native/verify_runtime.py
RUN python -m venv /opt/venv \
    && pip install --require-hashes --only-binary=:all: -r requirements-installer.lock \
    && pip install --require-hashes -r requirements.lock \
    && python -c "import importlib.util; assert importlib.util.find_spec('lxml') is None" \
    && python /native/verify_runtime.py api
COPY --from=wheel-builder /wheels /wheels
RUN pip install --no-deps /wheels/driftwatch-*.whl \
    && rm -rf /wheels

# The sole privileged component owns packet filtering, not application data.
FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6 AS capture-firewall
RUN apk add --no-cache iptables zlib=1.3.2-r1
COPY scripts/capture_firewall.sh /usr/local/bin/capture-firewall
RUN chmod 0555 /usr/local/bin/capture-firewall
HEALTHCHECK --interval=5s --timeout=3s --start-period=5s --retries=3 \
    CMD test -f /tmp/firewall-ready && iptables -C OUTPUT -d 169.254.0.0/16 -j REJECT && ip6tables -S OUTPUT | head -1 | grep -q 'OUTPUT DROP'
CMD ["/usr/local/bin/capture-firewall"]

# --- Stage 4: isolated browser worker --------------------------------------
FROM python-base AS capture-worker
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright \
    HOME=/tmp

# Only this image receives Chromium and its system libraries. The process runs
# as a dedicated non-root UID; the platform supplies a read-only root filesystem
# and bounded tmpfs at runtime (see docker-compose.yml / docs/DEPLOY.md).
COPY docker/native/worker.apk.lock /native/worker.apk.lock
COPY docker/native/verify_browser.py /native/verify_browser.py
COPY --from=native-builder /native-packages /opt/driftwatch-native/x86_64
COPY docker/native/verify_backports.py /opt/driftwatch-native/verify_backports.py
# Only this local, source/hash-verified repository is unsigned. Official Wolfi
# packages are verified first without --allow-untrusted. Package versions remain
# truthful and full APK records/checksums are generated by the rebuild.
RUN apk add --no-cache $(awk '{sub(/\r$/, "")} NF && !/^#/ && !/@driftwatch-native/' /native/worker.apk.lock) \
    && printf '@driftwatch-native /opt/driftwatch-native\n' > /opt/driftwatch-native/repositories \
    && apk add --repositories-file /opt/driftwatch-native/repositories --no-cache --no-network --allow-untrusted libx11@driftwatch-native=1.8.13-r7 libxrender@driftwatch-native=0.9.12-r9 \
    && python /opt/driftwatch-native/verify_backports.py \
    && python /native/verify_runtime.py worker \
    && playwright install --only-shell chromium \
    && python /native/verify_browser.py \
    && addgroup -g 10002 capture-worker \
    && adduser -D -H -u 10002 -G capture-worker capture-worker \
    && mkdir -p /ms-playwright /tmp \
    && chown -R capture-worker:capture-worker /ms-playwright /tmp
RUN pip check \
    && python -m pip uninstall -y pip \
    && python -c "import pathlib,ensurepip,shutil; shutil.rmtree(pathlib.Path(ensurepip.__file__).parent)" \
    && python -c "import importlib.util; assert all(importlib.util.find_spec(x) is None for x in ('pip', 'ensurepip'))"
USER capture-worker

EXPOSE 8090
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8090/livez')"

CMD ["driftwatch-capture-worker"]

# --- Stage 5: API, scheduler, and SPA runtime ------------------------------
FROM python-base AS runtime
ENV DRIFTWATCH_HOST=0.0.0.0 \
    DRIFTWATCH_DATA_DIR=/data

COPY --from=web /web/dist ./web/dist
# Include the exact source tree used by this image for inspection.
COPY --from=source /driftwatch-source.tar.gz ./web/dist/driftwatch-source.tar.gz
# Alembic migrations live at the repo root and pip does not package them, so copy
# them beside the working directory; the app resolves them from here at startup.
COPY migrations ./migrations
COPY alembic.ini ./

# Drop root: run as an unprivileged user that owns only the writable data path.
RUN addgroup -g 10001 driftwatch \
    && adduser -D -u 10001 -G driftwatch driftwatch \
    && mkdir -p /data \
    && chown -R driftwatch:driftwatch /app /data
RUN pip check \
    && python -m pip uninstall -y pip \
    && python -c "import pathlib,ensurepip,shutil; shutil.rmtree(pathlib.Path(ensurepip.__file__).parent)" \
    && python -c "import importlib.util; assert all(importlib.util.find_spec(x) is None for x in ('pip', 'ensurepip'))"
USER driftwatch

# /data holds SQLite, logs, backups, and uploaded branding. Postgres removes only
# the database file requirement; branding still needs durable object/file storage.
VOLUME ["/data"]
EXPOSE 8000
# Honour $PORT (set by platforms like Railway) so the check targets the real bind.
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD python -c "import json,os,urllib.request; p=json.load(urllib.request.urlopen('http://127.0.0.1:'+os.environ.get('PORT','8000')+'/healthz')); assert p['status']=='ok' and p['routing_ready']"

CMD ["driftwatch"]

# Railway and similar source builders normally build the last stage. A worker
# service can set DRIFTWATCH_IMAGE_TARGET=capture-worker as a Docker build arg;
# the API keeps the default runtime target.
FROM ${DRIFTWATCH_IMAGE_TARGET} AS final
