"""add organization plan and limits

Revision ID: 54eb8a9201c3
Revises: ef267a3ce89b
Create Date: 2026-06-19 21:21:09.729766

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54eb8a9201c3"
down_revision: str | Sequence[str] | None = "ef267a3ce89b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        # server_default backfills existing rows; new rows get the model default.
        batch_op.add_column(
            sa.Column("plan", sa.String(length=40), nullable=False, server_default="trial")
        )
        batch_op.add_column(sa.Column("max_sites", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("monthly_ai_check_limit", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_column("monthly_ai_check_limit")
        batch_op.drop_column("max_sites")
        batch_op.drop_column("plan")

    # ### end Alembic commands ###
